import { Octokit } from 'octokit';
import { Flag } from '@prisma/client';
import { analyzeFlag } from './cleanup-rules';

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const owner = process.env.GITHUB_REPO_OWNER!;
const repo = process.env.GITHUB_REPO_NAME!;

export async function createCleanupIssue(flag: Flag) {
  const analysis = analyzeFlag(flag);

  const title = `🧹 Cleanup feature flag: ${flag.key}`;

  const body = `## 🤖 Automated Feature Flag Cleanup

This issue was automatically created by the Feature Flag Cleanup system.

### 📊 Flag Details

- **Flag Key:** \`${flag.key}\`
- **Flag Name:** ${flag.name}
- **Description:** ${flag.description || 'N/A'}
- **Created:** ${flag.createdAt.toLocaleDateString()} (${
    analysis.ageInDays
  } days ago) by @${flag.createdBy}
- **Rollout Status:** ${flag.rolloutPercent}% enabled
- **Last Evaluation:** ${
    flag.lastEvaluatedAt?.toLocaleDateString() || 'Never'
  } ${analysis.daysSinceEval ? `(${analysis.daysSinceEval} days ago)` : ''}

### ⚠️ Why This Flag Should Be Removed

${analysis.reason}

### 🛠️ Cleanup Instructions for @copilot

Please remove the feature flag \`${
    flag.key
  }\` from the codebase by following these steps:

1. **Search for flag usage:** Find all occurrences of \`${
    flag.key
  }\` in the codebase
   - Look for patterns like: \`flags.${flag.key}\`, \`featureFlags['${
    flag.key
  }']\`, etc.

2. **Remove flag checks:** Remove all conditional logic that checks this flag
   - Example: \`if (flags.${flag.key}) { ... }\`

3. **Keep enabled code path:** Since this flag is 100% enabled, keep the code that runs when the flag is \`true\`
   - Remove the \`if\` statement and keep the code inside the "enabled" branch

4. **Remove flag definition:** Remove the flag from configuration files
   - Check: \`config/flags.json\`, \`lib/flags.ts\`, environment variables, etc.

5. **Update tests:** Remove or update tests that reference this flag
   - Remove test cases for the "disabled" state
   - Update tests to assume the feature is always enabled

6. **Clean up imports:** Remove any imports related to this flag if they're no longer needed

### 📁 Expected Files to Modify

Based on typical patterns, this flag likely appears in:
- \`src/\` or \`app/\` directory (application code)
- \`components/\` directory (React components)
- \`lib/\` or \`utils/\` directory (utilities)
- \`tests/\` or \`__tests__/\` directory (test files)
- Configuration files (\`flags.json\`, \`config.ts\`, \`.env\`, etc.)

### ✅ Safety Checklist

- [x] Flag has been 100% enabled for >30 days
- [x] No evaluations detected in the last ${analysis.daysSinceEval} days
- [x] Cleanup instructions provided
- [x] Flag creator notified (@${flag.createdBy})

### 🔄 Next Steps

1. **Review this issue** to confirm the flag should be removed
2. **Wait for @copilot** to create a pull request with the changes
3. **Review the PR** carefully - check that the correct code path was kept
4. **Approve and merge** the PR to complete the cleanup
5. **This issue will auto-close** when the PR is merged

---

**⏰ Lifecycle:** This issue will be automatically closed when the cleanup PR is merged or after 7 days if no action is taken.

**🏷️ Labels:** This issue is labeled \`automated-cleanup\` and can be filtered from your main issue view using: \`is:issue label:automated-cleanup\`

**📊 Dashboard:** Track cleanup status at your dashboard

---

Generated by **Feature Flag Cleanup MVP** • *Focus on features, not flag maintenance*
`;

  try {
    const response = await octokit.rest.issues.create({
      owner,
      repo,
      title,
      body,
      labels: ['automated-cleanup', 'technical-debt', 'feature-flag', 'bot'],
      // assignees: ['copilot'],
      assignees: ['lengieng'],
    });

    console.log(
      `✅ Created GitHub issue #${response.data.number}: ${response.data.html_url}`
    );

    return {
      url: response.data.html_url,
      number: response.data.number,
    };
  } catch (error) {
    console.error('❌ Failed to create GitHub issue:', error);
    throw error;
  }
}

export async function verifyGitHubConfig() {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is not set in environment variables');
  }
  if (!owner || !repo) {
    throw new Error('GITHUB_REPO_OWNER or GITHUB_REPO_NAME is not set');
  }

  try {
    // Verify repo access
    await octokit.rest.repos.get({ owner, repo });
    return { success: true, owner, repo };
  } catch (error) {
    throw new Error(
      `Cannot access GitHub repo ${owner}/${repo}. Check your token and repo settings.`
    );
  }
}
